"""BacktestHistory

Revision ID: 22205aaa5668
Revises: d5152c5e062f
Create Date: 2026-01-11 17:26:52.997143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22205aaa5668'
down_revision: Union[str, None] = 'd5152c5e062f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('strategy', sa.String(), nullable=False),
    sa.Column('asset_ids', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('tickers', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('initial_cash', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('total_invested', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('final_value', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('total_return_abs', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('total_return_pct', sa.DECIMAL(precision=10, scale=6), nullable=False),
    sa.Column('avg_daily_return', sa.DECIMAL(precision=10, scale=6), nullable=False),
    sa.Column('sharpe_ratio', sa.DECIMAL(precision=10, scale=6), nullable=False),
    sa.Column('max_drawdown', sa.DECIMAL(precision=10, scale=6), nullable=False),
    sa.Column('max_drawdown_duration', sa.Integer(), nullable=False),
    sa.Column('volatility', sa.DECIMAL(precision=10, scale=6), nullable=False),
    sa.Column('investments_made', sa.Integer(), nullable=False),
    sa.Column('peak_value', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('trough_value', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('trading_days', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_history_id'), 'backtest_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_backtest_history_id'), table_name='backtest_history')
    op.drop_table('backtest_history')
    # ### end Alembic commands ###
