"""OHLC

Revision ID: 2bfba3bd0706
Revises: a8bb9c972163
Create Date: 2025-10-10 12:48:11.563271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bfba3bd0706'
down_revision: Union[str, None] = 'a8bb9c972163'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timeseries', sa.Column('open', sa.Float(), nullable=True))
    op.add_column('timeseries', sa.Column('high', sa.Float(), nullable=False))
    op.add_column('timeseries', sa.Column('low', sa.Float(), nullable=False))
    op.add_column('timeseries', sa.Column('adj_close', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timeseries', 'adj_close')
    op.drop_column('timeseries', 'low')
    op.drop_column('timeseries', 'high')
    op.drop_column('timeseries', 'open')
    # ### end Alembic commands ###
