"""Initial migration

Revision ID: 6209ddfd9811
Revises:
Create Date: 2025-04-03 23:56:16.843067

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6209ddfd9811"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("asset_name", sa.String(), nullable=False),
        sa.Column("ticker", sa.String(), nullable=False),
        sa.Column("last_updated", sa.DateTime(), nullable=True),
        sa.Column("asset_type", sa.String(), nullable=True),
        sa.Column("currency", sa.String(), nullable=True),
        sa.Column("sector", sa.String(), nullable=True),
        sa.Column("country", sa.String(), nullable=True),
        sa.Column("market_cap", sa.BigInteger(), nullable=True),
        sa.Column("asset_class", sa.String(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ticker"),
    )
    op.create_index("ix_assets_asset_name", "assets", ["asset_name"], unique=False)
    op.create_index("ix_assets_ticker", "assets", ["ticker"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "portfolio",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("portfolio_name", sa.String(), nullable=False),
        sa.Column("asset_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Float(), nullable=False),
        sa.Column("purchase_price", sa.Float(), nullable=True),
        sa.Column("purchase_date", sa.DateTime(), nullable=True),
        sa.CheckConstraint("quantity >= 0", name="check_quantity_nonnegative"),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "portfolio_name", "asset_id"),
    )
    op.create_index("ix_portfolio_asset_id", "portfolio", ["asset_id"], unique=False)
    op.create_index(
        "ix_portfolio_portfolio_name", "portfolio", ["portfolio_name"], unique=False
    )
    op.create_index("ix_portfolio_user_id", "portfolio", ["user_id"], unique=False)
    op.create_table(
        "timeseries",
        sa.Column("asset_id", sa.Integer(), nullable=False),
        sa.Column("close", sa.Float(), nullable=False),
        sa.Column("volume", sa.BigInteger(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
        ),
        sa.PrimaryKeyConstraint("asset_id", "timestamp"),
    )
    op.create_index("ix_timeseries_asset_id", "timeseries", ["asset_id"], unique=False)
    op.create_index(
        "ix_timeseries_timestamp", "timeseries", ["timestamp"], unique=False
    )
    op.create_table(
        "watchlist_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("asset_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_watchlist_asset_id", "watchlist_items", ["asset_id"], unique=False
    )
    op.create_index(
        "ix_watchlist_user_asset",
        "watchlist_items",
        ["user_id", "asset_id"],
        unique=False,
    )
    op.create_index(
        "ix_watchlist_user_id", "watchlist_items", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_watchlist_user_id", table_name="watchlist_items")
    op.drop_index("ix_watchlist_user_asset", table_name="watchlist_items")
    op.drop_index("ix_watchlist_asset_id", table_name="watchlist_items")
    op.drop_table("watchlist_items")
    op.drop_index("ix_timeseries_timestamp", table_name="timeseries")
    op.drop_index("ix_timeseries_asset_id", table_name="timeseries")
    op.drop_table("timeseries")
    op.drop_index("ix_portfolio_user_id", table_name="portfolio")
    op.drop_index("ix_portfolio_portfolio_name", table_name="portfolio")
    op.drop_index("ix_portfolio_asset_id", table_name="portfolio")
    op.drop_table("portfolio")
    op.drop_table("users")
    op.drop_index("ix_assets_ticker", table_name="assets")
    op.drop_index("ix_assets_asset_name", table_name="assets")
    op.drop_table("assets")
    # ### end Alembic commands ###
