"""WatchlistAlertPercentageChange

Revision ID: b71dbf93e944
Revises: de9557d03bd9
Create Date: 2025-12-04 10:44:49.340868

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b71dbf93e944"
down_revision: Union[str, None] = "de9557d03bd9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "watchlist_items",
        sa.Column("alert_percentage_change", sa.Double(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("watchlist_items", "alert_percentage_change")
    # ### end Alembic commands ###
