"""EnforceSinglePriceUpdateRow

Revision ID: d5152c5e062f
Revises: dc77f58ec078
Create Date: 2025-12-23 17:36:03.936971

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd5152c5e062f'
down_revision: Union[str, None] = 'dc77f58ec078'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_update', sa.Column('singleton', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'price_update', ['singleton'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'price_update', type_='unique')
    op.drop_column('price_update', 'singleton')
    # ### end Alembic commands ###
