"""PriceUpdateTable

Revision ID: dc77f58ec078
Revises: fa52323efba4
Create Date: 2025-12-23 11:38:04.872599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc77f58ec078'
down_revision: Union[str, None] = 'fa52323efba4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_update',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price_update')
    # ### end Alembic commands ###
