export const assetsData = [
  {
    asset: "Apple Inc.",
    ticker: "AAPL",
    volume: "10M",
    marketCap: "2.5T",
    dailyPriceChange: "+$2.50",
    dailyPercentChange: "+1.7%",
    latestPrice: "$150.00",
  },
  {
    asset: "Gold",
    ticker: "GC=F",
    volume: "500K",
    marketCap: "N/A",
    dailyPriceChange: "-$5.00",
    dailyPercentChange: "-0.3%",
    latestPrice: "$1,850.00",
  },
  {
    asset: "Tesla",
    ticker: "TSLA",
    volume: "15M",
    marketCap: "700B",
    dailyPriceChange: "+$10.00",
    dailyPercentChange: "+1.4%",
    latestPrice: "$700.00",
  },
  {
    asset: "Amazon",
    ticker: "AMZN",
    volume: "8M",
    marketCap: "1.6T",
    dailyPriceChange: "+$5.00",
    dailyPercentChange: "+0.8%",
    latestPrice: "$3,200.00",
  },
  {
    asset: "Microsoft",
    ticker: "MSFT",
    volume: "12M",
    marketCap: "2.3T",
    dailyPriceChange: "+$3.00",
    dailyPercentChange: "+1.0%",
    latestPrice: "$280.00",
  },
  {
    asset: "Alphabet",
    ticker: "GOOGL",
    volume: "6M",
    marketCap: "1.5T",
    dailyPriceChange: "+$4.00",
    dailyPercentChange: "+1.2%",
    latestPrice: "$2,800.00",
  },
  {
    asset: "Facebook",
    ticker: "FB",
    volume: "5M",
    marketCap: "900B",
    dailyPriceChange: "+$2.00",
    dailyPercentChange: "+0.5%",
    latestPrice: "$350.00",
  },
  {
    asset: "Netflix",
    ticker: "NFLX",
    volume: "4M",
    marketCap: "250B",
    dailyPriceChange: "+$1.00",
    dailyPercentChange: "+0.4%",
    latestPrice: "$600.00",
  },
  {
    asset: "NVIDIA",
    ticker: "NVDA",
    volume: "7M",
    marketCap: "500B",
    dailyPriceChange: "+$6.00",
    dailyPercentChange: "+1.5%",
    latestPrice: "$800.00",
  },
  {
    asset: "Adobe",
    ticker: "ADBE",
    volume: "3M",
    marketCap: "300B",
    dailyPriceChange: "+$2.00",
    dailyPercentChange: "+0.7%",
    latestPrice: "$500.00",
  },
  {
    asset: "Intel",
    ticker: "INTC",
    volume: "10M",
    marketCap: "200B",
    dailyPriceChange: "+$1.50",
    dailyPercentChange: "+0.9%",
    latestPrice: "$50.00",
  },
  {
    asset: "AMD",
    ticker: "AMD",
    volume: "9M",
    marketCap: "150B",
    dailyPriceChange: "+$2.00",
    dailyPercentChange: "+1.3%",
    latestPrice: "$100.00",
  },
  {
    asset: "Cisco",
    ticker: "CSCO",
    volume: "8M",
    marketCap: "220B",
    dailyPriceChange: "+$1.00",
    dailyPercentChange: "+0.5%",
    latestPrice: "$60.00",
  },
  {
    asset: "Oracle",
    ticker: "ORCL",
    volume: "6M",
    marketCap: "180B",
    dailyPriceChange: "+$1.50",
    dailyPercentChange: "+0.8%",
    latestPrice: "$70.00",
  },
  {
    asset: "Salesforce",
    ticker: "CRM",
    volume: "5M",
    marketCap: "250B",
    dailyPriceChange: "+$3.00",
    dailyPercentChange: "+1.1%",
    latestPrice: "$250.00",
  },
  {
    asset: "IBM",
    ticker: "IBM",
    volume: "4M",
    marketCap: "120B",
    dailyPriceChange: "+$1.00",
    dailyPercentChange: "+0.6%",
    latestPrice: "$140.00",
  },
  {
    asset: "PayPal",
    ticker: "PYPL",
    volume: "7M",
    marketCap: "300B",
    dailyPriceChange: "+$2.50",
    dailyPercentChange: "+1.0%",
    latestPrice: "$250.00",
  },
  {
    asset: "Square",
    ticker: "SQ",
    volume: "6M",
    marketCap: "100B",
    dailyPriceChange: "+$1.50",
    dailyPercentChange: "+0.9%",
    latestPrice: "$200.00",
  },
  {
    asset: "Shopify",
    ticker: "SHOP",
    volume: "5M",
    marketCap: "150B",
    dailyPriceChange: "+$3.00",
    dailyPercentChange: "+1.2%",
    latestPrice: "$1,500.00",
  },
  {
    asset: "Spotify",
    ticker: "SPOT",
    volume: "4M",
    marketCap: "50B",
    dailyPriceChange: "+$1.00",
    dailyPercentChange: "+0.8%",
    latestPrice: "$300.00",
  },
  {
    asset: "Uber",
    ticker: "UBER",
    volume: "10M",
    marketCap: "90B",
    dailyPriceChange: "+$1.00",
    dailyPercentChange: "+0.7%",
    latestPrice: "$45.00",
  },
  {
    asset: "Lyft",
    ticker: "LYFT",
    volume: "8M",
    marketCap: "20B",
    dailyPriceChange: "+$0.50",
    dailyPercentChange: "+0.6%",
    latestPrice: "$30.00",
  },
  {
    asset: "Airbnb",
    ticker: "ABNB",
    volume: "6M",
    marketCap: "100B",
    dailyPriceChange: "+$2.00",
    dailyPercentChange: "+1.0%",
    latestPrice: "$150.00",
  },
  {
    asset: "Zoom",
    ticker: "ZM",
    volume: "5M",
    marketCap: "80B",
    dailyPriceChange: "+$1.50",
    dailyPercentChange: "+0.9%",
    latestPrice: "$400.00",
  },
  {
    asset: "Slack",
    ticker: "WORK",
    volume: "4M",
    marketCap: "30B",
    dailyPriceChange: "+$0.50",
    dailyPercentChange: "+0.5%",
    latestPrice: "$40.00",
  },
  {
    asset: "Pinterest",
    ticker: "PINS",
    volume: "7M",
    marketCap: "50B",
    dailyPriceChange: "+$1.00",
    dailyPercentChange: "+0.8%",
    latestPrice: "$70.00",
  },
  {
    asset: "Snap",
    ticker: "SNAP",
    volume: "6M",
    marketCap: "60B",
    dailyPriceChange: "+$1.50",
    dailyPercentChange: "+1.0%",
    latestPrice: "$80.00",
  },
  {
    asset: "Twitter",
    ticker: "TWTR",
    volume: "5M",
    marketCap: "40B",
    dailyPriceChange: "+$1.00",
    dailyPercentChange: "+0.7%",
    latestPrice: "$50.00",
  },
  {
    asset: "Baidu",
    ticker: "BIDU",
    volume: "4M",
    marketCap: "70B",
    dailyPriceChange: "+$2.00",
    dailyPercentChange: "+1.1%",
    latestPrice: "$200.00",
  },
  {
    asset: "Alibaba",
    ticker: "BABA",
    volume: "8M",
    marketCap: "600B",
    dailyPriceChange: "+$3.00",
    dailyPercentChange: "+1.0%",
    latestPrice: "$250.00",
  },
];
